name: Preview DNS Changes

on:
  pull_request:
    branches:
      - main
    paths:
      - "domains/*"
      - ".github/workflows/preview-records.yml"
      - "utils/reserved.json"
      - "dnsconfig.js"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  preview:
    name: Preview DNS changes
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate creds.json
        run: echo '{"cloudflare":{"TYPE":"CLOUDFLAREAPI","apitoken":"$CLOUDFLARE_API_TOKEN"}}' > creds.json
      - name: DNSControl preview
        uses: amaan-igs/dnscontrol-action@v1
        id: dnscontrol_preview
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          args: preview
          config_file: dnsconfig.js
          creds_file: creds.json
      - name: Preview pull request comment
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            ## DNS Preview Results
            ```
            ${{ steps.dnscontrol_preview.outputs.preview_comment }}
            ```
          check_for_duplicate_msg: true
