name: Publish DNS records

on:
  push:
    branches:
      - main
      - 'ci/*'
    paths:
      - "domains/*"
      - ".github/workflows/publish-records.yml"
      - "util/reserved.json"
      - "dnsconfig.js"
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-publish

jobs:
  dns:
    name: DNS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate creds.json
        run: echo '{"cloudflare":{"TYPE":"CLOUDFLAREAPI","apitoken":"$CLOUDFLARE_API_TOKEN"}}' > creds.json

      - name: Push DNS records
        uses: koenrh/dnscontrol-action@v3
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          args: push
          config_file: dnsconfig.js
          creds_file: creds.json